- alias: Reload Automations on automations.yaml Change
  id: 7ee9869743da4092b56c2bace5b494ad
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.path == '/config/automations.yaml' }}"
  action:
    - service: automation.reload
- alias: Reload Scripts on scripts.yaml Change
  id: af73319f1d7b46458e66c5d48a148073
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.path == '/config/scripts.yaml' }}"
  action:
    - service: script.reload
- alias: Reload Lovelace on ui-lovelace.yaml Change
  id: 7a963be5b38948d789ee500be0c9bcf4
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.path == '/config/ui-lovelace.yaml' }}"
  action:
    - service: lovelace.reload
- alias: Reload Scenes on scenes.yaml Change
  id: dd4150004ba64d40b8d5ac1a99e9ea9a
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.path == '/config/scenes.yaml' }}"
  action:
    - service: scene.reload
- alias: Reload Configuration on configuration.yaml Change
  id: e4e617ac60e24886ad0cf7b2782f018f
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.path == '/config/configuration.yaml'}}"
  action:
    - service: homeassistant.reload_core_config
