# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  allowlist_external_dirs:
    - "/config"

api:

group:
  garmin:
    name: Garmin
    entities:
      - light.orein_smart_bulb_001
      - light.orein_smart_bulb_002
      - light.orein_smart_bulb_003
      - light.orein_smart_bulb_004

fan:
  - platform: template
    fans:
      air_purifier_virtual:
        unique_id: "air_purifier_virtual"
        friendly_name: "Air Purifier Virtual"
        value_template: "{{ states('fan.zhimi_airpurifier_mb3') }}"
        percentage_template: >
          {{ ((states('number.zhimi_airpurifier_mb3_favorite_level') | int + 1) * 100/15) | round(0) }}
        turn_on:
          service: script.turn_air_purifier_on
          data_template:
            percentage: "{{ ((states('number.zhimi_airpurifier_mb3_favorite_level') | int + 1) * 100/15) | round(0) }}"
            entity_id: fan.zhimi_airpurifier_mb3
            virtual_entity_id: fan.air_purifier_virtual
        turn_off:
          service: fan.turn_off
          data:
            entity_id: fan.zhimi_airpurifier_mb3
        set_percentage:
          service: script.set_air_purifier_speed
          data_template:
            percentage: "{{ percentage }}"
            entity_id: fan.zhimi_airpurifier_mb3
            favorite_level_entity_id: number.zhimi_airpurifier_mb3_favorite_level
        speed_count: 15
      air_purifier_virtual_2:
        unique_id: "air_purifier_virtual_2"
        friendly_name: "Air Purifier Virtual 2"
        value_template: "{{ states('fan.zhimi_airpurifier_mb3_2') }}"
        percentage_template: >
          {{ ((states('number.zhimi_airpurifier_mb3_favorite_level_2') | int + 1) * 100/15) | round(0) }}
        turn_on:
          service: script.turn_air_purifier_on
          data_template:
            percentage: "{{ ((states('number.zhimi_airpurifier_mb3_favorite_level_2') | int + 1) * 100/15) | round(0) }}"
            entity_id: fan.zhimi_airpurifier_mb3_2
            virtual_entity_id: fan.air_purifier_virtual_2
        turn_off:
          service: fan.turn_off
          data:
            entity_id: fan.zhimi_airpurifier_mb3_2
        set_percentage:
          service: script.set_air_purifier_speed
          data_template:
            percentage: "{{ percentage }}"
            entity_id: fan.zhimi_airpurifier_mb3_2
            favorite_level_entity_id: number.zhimi_airpurifier_mb3_favorite_level_2
        speed_count: 15

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
